import { useCallback, useEffect, useMemo, useState } from 'react';
import { evaluatePrinterReadiness } from '@printerops/domain';
import { apiFetch } from '../api/client.js';
import { errorMessage } from '../api/errors.js';
import { useLocale } from '../i18n/index.js';
import { useApiResource } from '../hooks/useApiResource.js';
import { sanitizePreviewHtml } from '../lib/previewHtml.js';
import {
  Alert,
  Badge,
  Button,
  Checkbox,
  Chip,
  CodeBlock,
  Dialog,
  EmptyState,
  ErrorBanner,
  CardDetailItem,
  CardDetail,
  FormField,
  Inline,
  Input,
  LoadingState,
  PageLayout,
  SectionHeading,
  Select,
  Stack,
  StatusIndicator,
  Text,
  Textarea,
} from '../components/ui/index.js';

interface Printer {
  id: string;
  code: string;
  name: string;
  location?: string;
  protocol: string;
  connectionUri: string;
  isActive: boolean;
  status?: {
    code: string;
    checkedAt: string;
    detected?: boolean;
    workOffline?: boolean | null;
    rawStatus?: string;
    rawState?: string;
  };
  capabilities?: {
    colorSupported: boolean;
    duplexSupported: boolean;
    maxPageWidth: number;
    maxPageHeight: number;
    maxCopies: number;
  };
  allowedTemplates?: string[];
  maxCopiesPerJob?: number;
}
interface Template {
  id: string;
  templateCode: string;
  name: string;
  engine: string;
  status: string;
  paperProfileId?: string;
}
interface Paper {
  id: string;
  code: string;
  name: string;
  widthMm: number;
  heightMm: number;
  dpi: number;
  orientation: 'portrait' | 'landscape';
}
interface Preview {
  renderedPreview: string;
  renderedPrintPayload: string;
  warnings: string[];
  renderTimeMs: number;
}

interface SandboxJobResult {
  id: string;
  status: string;
  errorCode?: string;
  errorMessage?: string;
}

const TERMINAL_JOB_STATUSES = new Set([
  'SUCCESS', 'UNVERIFIED', 'FAILED', 'TIMEOUT', 'CANCELLED', 'DUPLICATE_RETURNED',
]);

async function waitForSandboxJob(jobId: string): Promise<SandboxJobResult> {
  // The backend may spend up to 45s submitting through WebView2, 30s
  // correlating the Windows job, and 90s waiting for the physical page
  // counter. Keep the UI attached long enough to receive that persisted
  // terminal verdict instead of timing out a few milliseconds before it.
  const deadline = Date.now() + 210_000;
  while (Date.now() < deadline) {
    const job = await apiFetch<SandboxJobResult>(`/jobs/${jobId}`);
    if (TERMINAL_JOB_STATUSES.has(job.status)) return job;
    await new Promise((resolve) => setTimeout(resolve, 750));
  }
  throw new Error('PRINT_STATUS_TIMEOUT');
}

type SandboxTemplateRef = Pick<Template, 'id' | 'paperProfileId'> & Partial<Pick<Template, 'engine'>>;

/**
 * Each paper profile has an HTML companion template generated by the API.
 * Resolving it here lets a paper-first sandbox workflow render without making
 * the operator select the same profile again through a template.
 */
export function getCompanionTemplateId(templates: SandboxTemplateRef[], paperProfileId: string): string {
  return templates.find(
    (template) => template.paperProfileId === paperProfileId && template.engine === 'HTML',
  )?.id ?? '';
}

/** A deliberately selected paper profile always wins over a template default. */
export function resolvePaperProfileId(currentPaperProfileId: string, template?: SandboxTemplateRef): string {
  return currentPaperProfileId || template?.paperProfileId || '';
}

const DEFAULT_PAYLOAD = '{"label":"Test Label","barcode":"ABC123","hn_masked":"HN***"}';

/**
 * What is left of this page's local styling.
 *
 * It used to carry a full parallel design system as inline objects — its own
 * input, label, primary/secondary button, toggle button and status-dot palette,
 * with `primaryBtn` painting the main action Deep Navy while every other page
 * used Action Blue. Those all resolve to shared components now. Only the
 * page's own section rhythm remains, because the sandbox column really is a
 * stack of rule-separated regions and nothing else in the product is.
 */
const sectionStyle: React.CSSProperties = { borderBottom: '1px solid var(--neutral-border)', padding: '0.85rem 0' };
const sectionLastStyle: React.CSSProperties = { padding: '0.85rem 0' };
const sectionTitleStyle: React.CSSProperties = {
  fontSize: 'var(--font-label-size)', fontWeight: 700, color: 'var(--neutral-deep)',
  letterSpacing: '0.04em', marginBottom: '0.6rem',
};
const cardStyle: React.CSSProperties = {
  background: 'var(--neutral-surface)', padding: '0 var(--spacing-xl)',
  border: '1px solid var(--neutral-border)', borderRadius: 'var(--rounded-lg)',
};

export default function TemplateSandbox() {
  const { t } = useLocale();
  const [templates, setTemplates] = useState<Template[]>([]);
  const [papers, setPapers] = useState<Paper[]>([]);
  const [printers, setPrinters] = useState<Printer[]>([]);

  const [templateId, setTemplateId] = useState('');
  const [paperProfileId, setPaperProfileId] = useState('');
  const [printerId, setPrinterId] = useState('');
  const [payload, setPayload] = useState(DEFAULT_PAYLOAD);

  // Print options
  const [copies, setCopies] = useState(1);
  const [duplex, setDuplex] = useState(false);
  const [colorMode, setColorMode] = useState<'auto' | 'color' | 'monochrome'>('auto');
  const [priority, setPriority] = useState<'low' | 'normal' | 'high' | 'urgent'>('normal');

  const [preview, setPreview] = useState<Preview | null>(null);
  const [loading, setLoading] = useState({ init: true, render: false, print: false });
  const [error, setError] = useState('');
  const [toast, setToast] = useState<{ type: 'success' | 'error'; msg: string } | null>(null);
  const [confirmPrintOpen, setConfirmPrintOpen] = useState(false);
  const [printAcknowledged, setPrintAcknowledged] = useState(false);
  const [submittedJobId, setSubmittedJobId] = useState<string | null>(null);

  // ---- load reference data ----
  // Each list was `.catch(() => {})`: a failure left the three dropdowns empty
  // and the operator with no way to tell "nothing configured" from "the API is
  // down" — on the one page whose whole purpose is diagnosing print setup.
  const fetchReferenceData = useCallback(async () => {
    const [templates, papers, printers] = await Promise.all([
      apiFetch<Template[]>('/v1/sandbox/templates'),
      apiFetch<Paper[]>('/v1/paper-profiles'),
      apiFetch<Printer[]>('/printers'),
    ]);
    return { templates, papers, printers };
  }, []);

  const reference = useApiResource(fetchReferenceData);

  useEffect(() => {
    if (!reference.data) return;
    setTemplates(reference.data.templates);
    setPapers(reference.data.papers);
    setPrinters(reference.data.printers);
    setLoading((s) => ({ ...s, init: false }));
  }, [reference.data]);

  useEffect(() => {
    if (reference.error != null) setLoading((s) => ({ ...s, init: false }));
  }, [reference.error]);

  const selectedTemplate = useMemo(() => templates.find((t) => t.id === templateId), [templates, templateId]);
  const selectedPrinter = useMemo(() => printers.find((p) => p.id === printerId), [printers, printerId]);

  // ---- toast auto-dismiss ----
  useEffect(() => {
    if (!toast) return;
    const timer = setTimeout(() => setToast(null), 4000);
    return () => clearTimeout(timer);
  }, [toast]);

  // ---- JSON validation ----
  const payloadError = useMemo(() => {
    try { JSON.parse(payload); return ''; } catch { return t('page.sandbox.jsonError'); }
  }, [payload]);

  const printerMaxCopies = selectedPrinter?.maxCopiesPerJob ?? selectedPrinter?.capabilities?.maxCopies;
  const duplexAvailable = Boolean(selectedPrinter?.capabilities?.duplexSupported);
  const colorAvailable = Boolean(selectedPrinter?.capabilities?.colorSupported);
  const copiesExceeded = printerMaxCopies != null && copies > printerMaxCopies;
  const templateAllowed = !selectedPrinter?.allowedTemplates || selectedPrinter.allowedTemplates.length === 0 || !selectedTemplate || selectedPrinter.allowedTemplates.includes(selectedTemplate.templateCode);
  const printerReadiness = evaluatePrinterReadiness({
    detected: selectedPrinter?.status?.detected,
    statusCode: selectedPrinter?.status?.code,
    rawStatus: selectedPrinter?.status?.rawStatus,
    rawState: selectedPrinter?.status?.rawState,
    workOffline: selectedPrinter?.status?.workOffline,
  });
  const printerReady = Boolean(selectedPrinter) && printerReadiness.ready;
  const printerReadinessWarning = printerReadiness.warning === 'unknown-status'
    ? t('page.sandbox.printerUnknownWarning')
    : printerReadiness.warning === 'status-unavailable'
      ? t('page.sandbox.printerStatusUnavailableWarning')
      : '';
  const canPrint = !!printerId && !!templateId && !payloadError && !copiesExceeded && templateAllowed && printerReady;
  const testPrintBlockedReason = !printerId
    ? t('page.sandbox.testPrintNeedsPrinter')
    : !templateId
      ? t('page.sandbox.testPrintNeedsTemplate')
      : payloadError
        ? t('page.sandbox.testPrintFixPayload')
        : copiesExceeded
          ? t('page.sandbox.testPrintReduceCopies')
          : !templateAllowed
            ? t('page.sandbox.testPrintChooseAllowedTemplate')
            : !printerReadiness.ready
              ? printerReadiness.blockedBy === 'not-detected'
                ? t('page.sandbox.testPrintNeedsStatus')
                : t('page.sandbox.testPrintBlockedByPrinter')
            : '';

  useEffect(() => {
    if (!duplexAvailable && duplex) setDuplex(false);
    if (!colorAvailable && colorMode === 'color') setColorMode('auto');
  }, [colorAvailable, colorMode, duplex, duplexAvailable]);

  function handlePaperProfileChange(nextPaperProfileId: string) {
    setPaperProfileId(nextPaperProfileId);
    setPreview(null);
    setError('');

    const companionTemplateId = getCompanionTemplateId(templates, nextPaperProfileId);
    if (companionTemplateId) setTemplateId(companionTemplateId);
  }

  function handleTemplateChange(nextTemplateId: string) {
    const nextTemplate = templates.find((template) => template.id === nextTemplateId);
    setTemplateId(nextTemplateId);
    setPaperProfileId((currentPaperProfileId) => resolvePaperProfileId(currentPaperProfileId, nextTemplate));
    setPreview(null);
    setError('');
  }

  // ---- actions ----
  async function renderPreview() {
    setError('');
    if (!templateId) { setError(t('page.sandbox.selectTemplateFirst')); return; }
    if (payloadError) { setError(payloadError); return; }
    setLoading((s) => ({ ...s, render: true }));
    try {
      const res = await apiFetch<Preview>('/v1/sandbox/render-preview', {
        method: 'POST',
        body: JSON.stringify({
          templateId,
          paperProfileId: paperProfileId || undefined,
          samplePayload: JSON.parse(payload) as Record<string, unknown>,
        }),
      });
      setPreview(res);
    } catch (err: unknown) {
      // A template that fails to render says WHY (bad placeholder, missing
      // paper profile); the generic sentence hid every one of those reasons.
      setError(`${t('page.sandbox.renderFailed')} ${errorMessage(err)}`);
    } finally {
      setLoading((s) => ({ ...s, render: false }));
    }
  }

  async function testPrint() {
    setError('');
    if (!canPrint) { setError(t('page.sandbox.printIncomplete')); return; }
    setLoading((s) => ({ ...s, print: true }));
    try {
      const res = await apiFetch<{
        accepted: boolean;
        jobId: string;
        traceId: string;
        status: string;
        warnings: string[];
        errorCode?: string;
        errorMessage?: string;
      }>('/v1/sandbox/test-print', {
        method: 'POST',
        body: JSON.stringify({
          templateId,
          paperProfileId: paperProfileId || undefined,
          printerId,
          printerCode: selectedPrinter?.code,
          copies,
          duplex,
          colorMode,
          priority,
          samplePayload: JSON.parse(payload) as Record<string, unknown>,
        }),
      });
      setSubmittedJobId(res.jobId);
      const completed = await waitForSandboxJob(res.jobId);
      if (completed.status === 'SUCCESS') {
        setToast({ type: 'success', msg: t('page.sandbox.printSuccess').replace('{jobId}', res.jobId.slice(0, 8)).replace('{copies}', String(copies)).replace('{printer}', selectedPrinter?.name ?? '') });
      } else {
        const summary = t('page.sandbox.printFailed').replace('{status}', completed.status);
        setToast({ type: 'error', msg: completed.errorMessage ? `${summary}: ${completed.errorMessage}` : summary });
      }
    } catch (err) {
      setToast({
        type: 'error',
        msg: err instanceof Error && err.message === 'PRINT_STATUS_TIMEOUT'
          ? t('page.sandbox.printStatusTimeout')
          : `${t('page.sandbox.printError')} ${errorMessage(err)}`,
      });
    } finally {
      setLoading((s) => ({ ...s, print: false }));
    }
  }

  function requestTestPrint() {
    if (!canPrint) { setError(t('page.sandbox.printIncomplete')); return; }
    setPrintAcknowledged(false);
    setConfirmPrintOpen(true);
  }

  return (
    <PageLayout
      className="template-sandbox-page"
      width="full"
      title={t('page.sandbox.title')}
      description={t('page.sandbox.description')}
    >

      {/* Reference data failed: the dropdowns below are empty because of this,
          not because nothing is configured. */}
      {reference.error != null && (
        <ErrorBanner
          error={reference.error}
          title={t('page.sandbox.referenceLoadFailed')}
          onRetry={reference.refresh}
        />
      )}

      {/* ===== Result ===== */}
      {toast && (
        <Alert tone={toast.type === 'success' ? 'success' : 'error'} onDismiss={() => setToast(null)} dismissLabel={t('common.close')}>
          {toast.msg}
        </Alert>
      )}

      {/* Physical output. The confirmation restates printer, template and copy
          count, and the acknowledgement stays a hard gate on the submit. */}
      <Dialog
        open={confirmPrintOpen}
        onClose={() => setConfirmPrintOpen(false)}
        title="Confirm physical test print"
        warning="This action will produce physical output. Generating a proof does not print."
        footer={<>
          <Button variant="secondary" onClick={() => setConfirmPrintOpen(false)}>Cancel</Button>
          <Button
            variant="danger"
            disabled={!printAcknowledged}
            busy={loading.print}
            busyLabel={t('page.sandbox.sending')}
            onClick={() => { setConfirmPrintOpen(false); void testPrint(); }}
          >
            Send physical test print
          </Button>
        </>}
      >
        <Stack gap="lg">
          <CardDetail>
            <CardDetailItem label="Printer">{selectedPrinter?.name ?? '—'}</CardDetailItem>
            <CardDetailItem label="Template">{selectedTemplate?.templateCode ?? '—'}</CardDetailItem>
            <CardDetailItem label="Copies">{copies}</CardDetailItem>
          </CardDetail>
          <Checkbox
            label="I understand this will produce physical output."
            checked={printAcknowledged}
            onChange={(event) => setPrintAcknowledged(event.target.checked)}
          />
        </Stack>
      </Dialog>

      {loading.init ? (
        <LoadingState label={t('page.sandbox.loading')} />
      ) : (
        <div className="template-sandbox-layout">
          {/* ===================== Config Panel ===================== */}
          <section style={cardStyle}>
            {/* --- Printer --- */}
            <div style={{ ...sectionStyle, paddingTop: '1.1rem' }}>
              <div style={sectionTitleStyle}>{t('page.sandbox.printer')}</div>
              <FormField label={t('page.sandbox.selectPrinter')}>
                {(control) => (
                  <Select {...control} value={printerId} onChange={(e) => setPrinterId(e.target.value)}>
                    <option value="">{t('page.sandbox.selectPrinterPlaceholder')}</option>
                    {printers.filter((p) => p.isActive).map((p) => (
                      <option key={p.id} value={p.id}>
                        {p.name} ({p.code}){p.location ? ` · ${p.location}` : ''}
                        {p.status ? ` · ${p.status.code}` : ''}
                      </option>
                    ))}
                  </Select>
                )}
              </FormField>
              <Text
                as="p"
                id="sandbox-capability-status"
                role="status"
                aria-live="polite"
                size="label"
                tone="muted"
              >
                {!selectedPrinter
                  ? t('page.sandbox.selectPrinterForOptions')
                  : [!duplexAvailable && t('page.sandbox.duplexUnavailable'), !colorAvailable && t('page.sandbox.colorUnavailable')].filter(Boolean).join(' ')}
              </Text>
              {/* Five identical inline-styled `<span>` pills, one of them
                  carrying a fourth copy of the device-status colour map. */}
              {selectedPrinter && (
                <Inline gap="xs">
                  {selectedPrinter.status && <StatusIndicator condition={selectedPrinter.status.code} />}
                  <Badge>{selectedPrinter.protocol}</Badge>
                  {selectedPrinter.capabilities?.duplexSupported && <Badge>{t('page.sandbox.duplexLabel')}</Badge>}
                  {selectedPrinter.capabilities?.colorSupported && <Badge>{t('page.sandbox.colorLabel')}</Badge>}
                  {printerMaxCopies != null && <Badge>{t('page.sandbox.maxCopiesLabel').replace('{n}', String(printerMaxCopies))}</Badge>}
                </Inline>
              )}
              {/* Was an emoji standing in for an icon; the alert carries the
                  severity in its own role and tone. */}
              {!templateAllowed && (
                <Alert tone="warning">
                  {t('page.sandbox.templateNotAllowed').replace('{code}', selectedTemplate?.templateCode ?? '')}
                </Alert>
              )}
              {printerReadinessWarning && (
                <Alert tone="warning">
                  {printerReadinessWarning}
                </Alert>
              )}
            </div>

            {/* --- Paper & Template --- */}
            <div style={sectionStyle}>
              <div style={sectionTitleStyle}>{t('page.sandbox.templatePaper')}</div>
              <FormField
                label={t('page.sandbox.paperProfile')}
                hint={paperProfileId ? t('page.sandbox.paperProfilePriorityHint') : undefined}
              >
                {(control) => (
                  <Select {...control} value={paperProfileId} onChange={(e) => handlePaperProfileChange(e.target.value)}>
                    <option value="">{t('page.sandbox.paperProfileDefault')}</option>
                    {papers.map((p) => (
                      <option key={p.id} value={p.id}>{p.code} ({p.widthMm}×{p.heightMm}mm, {p.dpi}dpi)</option>
                    ))}
                  </Select>
                )}
              </FormField>
              <Stack gap="xs">
                <FormField label={t('page.sandbox.template')}>
                  {(control) => (
                    <Select {...control} value={templateId} onChange={(e) => handleTemplateChange(e.target.value)}>
                      <option value="">{t('page.sandbox.selectTemplatePlaceholder')}</option>
                      {templates.map((tpl) => (
                        <option key={tpl.id} value={tpl.id}>{tpl.templateCode} — {tpl.name}</option>
                      ))}
                    </Select>
                  )}
                </FormField>
                {selectedTemplate && (
                  <Inline gap="xs">
                    <Badge>{selectedTemplate.engine}</Badge>
                    <Badge>{selectedTemplate.status}</Badge>
                  </Inline>
                )}
              </Stack>
            </div>

            {/* --- Print Options --- */}
            <div style={sectionStyle}>
              <div style={sectionTitleStyle}>{t('page.sandbox.printOptions')}</div>
              {/* Copy count drives how many physical labels come out, so it
                  keeps its stepper — but on shared controls. */}
              <Stack gap="xs">
                <FormField label={t('page.sandbox.copies')} error={copiesExceeded ? t('page.sandbox.copiesExceeded').replace('{max}', String(printerMaxCopies)) : undefined}>
                  {(control) => (
                    <Inline gap="xs" className="sandbox-copies">
                      <Button
                        variant="secondary"
                        size="sm"
                        aria-label={t('page.sandbox.copies')}
                        onClick={() => setCopies(Math.max(1, copies - 1))}
                      >
                        −
                      </Button>
                      <Input
                        {...control}
                        type="number"
                        min={1}
                        controlSize="sm"
                        invalid={copiesExceeded}
                        value={copies}
                        onChange={(e) => setCopies(Math.max(1, Number(e.target.value) || 1))}
                      />
                      <Button
                        variant="secondary"
                        size="sm"
                        aria-label={t('page.sandbox.copies')}
                        onClick={() => setCopies(copies + 1)}
                      >
                        +
                      </Button>
                    </Inline>
                  )}
                </FormField>
              </Stack>

              {/* Duplex — a two-state selection, so chips with a real pressed
                  state rather than two buttons tinted by an inline style. */}
              <Stack gap="xs">
                <Text size="label" tone="muted">{t('page.sandbox.duplex')}</Text>
                <Inline gap="xs">
                  <Chip selected={!duplex} onClick={() => setDuplex(false)}>
                    {t('page.sandbox.singleSided')}
                  </Chip>
                  <Chip
                    selected={duplex}
                    onClick={() => setDuplex(true)}
                    disabled={!duplexAvailable}
                    aria-describedby={!duplexAvailable ? 'sandbox-capability-status' : undefined}
                  >
                    {t('page.sandbox.doubleSidedShort')}
                  </Chip>
                </Inline>
              </Stack>

              {/* Color Mode */}
              <Stack gap="xs">
                <Text size="label" tone="muted">{t('page.sandbox.colorMode')}</Text>
                <Inline gap="xs">
                  {(['auto', 'color', 'monochrome'] as const).map((m) => (
                    <Chip
                      key={m}
                      selected={colorMode === m}
                      onClick={() => setColorMode(m)}
                      disabled={m === 'color' && !colorAvailable}
                      aria-describedby={m === 'color' && !colorAvailable ? 'sandbox-capability-status' : undefined}
                    >
                      {m === 'auto' ? t('page.sandbox.auto') : m === 'color' ? t('page.sandbox.color') : t('page.sandbox.monochrome')}
                    </Chip>
                  ))}
                </Inline>
              </Stack>

              {/* Priority. The coloured-circle emoji that used to prefix each
                  label were not an icon system — they render differently on
                  every platform and the word beside them already said it. */}
              <Stack gap="xs">
                <Text size="label" tone="muted">{t('page.sandbox.priority')}</Text>
                <Inline gap="xs">
                  {(['low', 'normal', 'high', 'urgent'] as const).map((p) => (
                    <Chip key={p} selected={priority === p} onClick={() => setPriority(p)}>
                      {p.charAt(0).toUpperCase() + p.slice(1)}
                    </Chip>
                  ))}
                </Inline>
              </Stack>
            </div>

            {/* --- Payload --- */}
            <details style={sectionLastStyle}>
              <summary style={{ ...sectionTitleStyle, cursor: 'pointer' }}>Expert payload</summary>
              <Stack gap="sm">
                <Text size="label" tone="muted">Edit JSON only when troubleshooting a template proof.</Text>
                <FormField label={t('page.sandbox.samplePayload')} error={payloadError ?? undefined}>
                  {(control) => (
                    <Textarea
                      {...control}
                      mono
                      rows={6}
                      invalid={Boolean(payloadError)}
                      value={payload}
                      onChange={(e) => setPayload(e.target.value)}
                    />
                  )}
                </FormField>
              </Stack>
            </details>

            {/* --- Actions ---
                Render and Print are deliberately different weights: rendering a
                proof is reversible and free, sending one puts paper through a
                device, so it carries the consequence variant and a confirmation. */}
            {error && <Alert tone="error">{error}</Alert>}
            <Inline gap="sm" className="sandbox-actions">
              <Button
                variant="secondary"
                onClick={() => void renderPreview()}
                busy={loading.render}
                busyLabel={t('page.sandbox.rendering')}
              >
                {t('page.sandbox.renderPreview')}
              </Button>
              <Button
                variant="danger"
                onClick={requestTestPrint}
                disabled={!canPrint}
                busy={loading.print}
                busyLabel={t('page.sandbox.sending')}
                aria-describedby={!canPrint ? 'sandbox-test-print-status' : undefined}
              >
                {t('page.sandbox.testPrint')}
              </Button>
            </Inline>
            {submittedJobId && (
              <Text as="p" role="status" aria-live="polite" size="label" tone="muted">
                Physical test print submitted.{' '}
                <a className="ui-link" href={`/jobs/${submittedJobId}`}>Open job {submittedJobId.slice(0, 8)}</a>{' '}
                to check its latest status.
              </Text>
            )}
            {!canPrint && (
              <Text as="p" id="sandbox-test-print-status" role="status" aria-live="polite" size="label" tone="muted">
                {t('page.sandbox.testPrintBlocked').replace('{reason}', testPrintBlockedReason)}
              </Text>
            )}
          </section>

          {/* ===================== Preview Panel ===================== */}
          <section style={{ ...cardStyle, padding: '1.25rem' }}>
            <SectionHeading
              title={t('page.sandbox.preview')}
              actions={preview ? <Text size="label" tone="muted">render {preview.renderTimeMs}ms</Text> : undefined}
            />

            {!preview ? (
              /* Was a giant printer emoji over a caption. The shared empty state
                 says the same thing without pretending to have an icon system. */
              <EmptyState title={t('page.sandbox.previewEmpty')} />
            ) : (
              <>
                {/* Preview canvas (Variant 1: Print Proof Workbench) */}
                <div className="sandbox-proof-workbench">
                  <div className="sandbox-proof-toolbar">
                    <Text size="label" tone="muted" className="sandbox-proof-dim">
                      {papers.find((p) => p.id === paperProfileId)?.code ?? 'Print Canvas'} ({papers.find((p) => p.id === paperProfileId) ? `${papers.find((p) => p.id === paperProfileId)!.widthMm}×${papers.find((p) => p.id === paperProfileId)!.heightMm}mm, ${papers.find((p) => p.id === paperProfileId)!.dpi} DPI` : 'Standard Proof'})
                    </Text>
                    <Text size="label" tone="muted" className="sandbox-proof-latency">{preview.renderTimeMs}ms</Text>
                  </div>
                  <div className="sandbox-paper-sheet">
                    <div dangerouslySetInnerHTML={{ __html: sanitizePreviewHtml(preview.renderedPreview) }} />
                  </div>
                </div>

                {/* Warnings */}
                {preview.warnings.length > 0 && (
                  <Alert tone="warning" title={t('page.sandbox.warnings')}>
                    <ul className="sandbox-warning-list">
                      {preview.warnings.map((w, i) => <li key={i}>{w}</li>)}
                    </ul>
                  </Alert>
                )}

                {/* Generated payload */}
                <Stack gap="xs">
                  <SectionHeading
                    level={3}
                    title={t('page.sandbox.generatedPayload')}
                    actions={
                      <Button
                        variant="secondary"
                        size="sm"
                        onClick={() => navigator.clipboard.writeText(preview.renderedPrintPayload)}
                      >
                        {t('common.copy')}
                      </Button>
                    }
                  />
                  {/* Was a dark inverted block — the only dark surface in a
                      light-first product, on a page that also shows proof paper. */}
                  <CodeBlock label={t('page.sandbox.generatedPayload')}>
                    {preview.renderedPrintPayload}
                  </CodeBlock>
                </Stack>
              </>
            )}

            {/* Print summary: what the next print would actually do, in one line. */}
            {(selectedPrinter || selectedTemplate) && (
              <Alert tone="info">
                <Text weight="semibold">{t('page.sandbox.printSummary')}:</Text>{' '}
                {selectedPrinter?.name ?? t('page.sandbox.summaryNoPrinter')}
                {' · '}
                {t('page.sandbox.copiesUnit').replace('{n}', String(copies))}
                {' · '}
                {duplex ? t('page.sandbox.doubleSidedShort') : t('page.sandbox.singleSidedShort')}
                {' · '}
                {colorMode === 'color' ? t('page.sandbox.colorShort') : colorMode === 'monochrome' ? t('page.sandbox.monochromeShort') : t('page.sandbox.auto')}
                {' · '}
                {priority}
                {selectedTemplate && ` · ${selectedTemplate.templateCode}`}
              </Alert>
            )}
          </section>
        </div>
      )}
    </PageLayout>
  );
}
