import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../api/client.js';
import { errorMessage } from '../api/errors.js';
import { useLocale } from '../i18n/index.js';
import { useApiResource } from '../hooks/useApiResource.js';
import { ErrorBanner } from '../components/PageState.js';
import { Dialog } from '../components/Dialog.js';
import { sanitizePreviewHtml } from '../lib/previewHtml.js';

interface Printer {
  id: string;
  code: string;
  name: string;
  location?: string;
  protocol: string;
  connectionUri: string;
  isActive: boolean;
  status?: { code: string; checkedAt: string };
  capabilities?: {
    colorSupported: boolean;
    duplexSupported: boolean;
    maxPageWidth: number;
    maxPageHeight: number;
    maxCopies: number;
  };
  allowedTemplates?: string[];
  maxCopiesPerJob?: number;
}
interface Template {
  id: string;
  templateCode: string;
  name: string;
  engine: string;
  status: string;
  paperProfileId?: string;
}
interface Paper {
  id: string;
  code: string;
  name: string;
  widthMm: number;
  heightMm: number;
  dpi: number;
  orientation: 'portrait' | 'landscape';
}
interface Preview {
  renderedPreview: string;
  renderedPrintPayload: string;
  warnings: string[];
  renderTimeMs: number;
}

interface SandboxJobResult {
  id: string;
  status: string;
  errorCode?: string;
  errorMessage?: string;
}

const TERMINAL_JOB_STATUSES = new Set([
  'SUCCESS', 'UNVERIFIED', 'FAILED', 'TIMEOUT', 'CANCELLED', 'DUPLICATE_RETURNED',
]);

async function waitForSandboxJob(jobId: string): Promise<SandboxJobResult> {
  // The backend may spend up to 45s submitting through WebView2, 30s
  // correlating the Windows job, and 90s waiting for the physical page
  // counter. Keep the UI attached long enough to receive that persisted
  // terminal verdict instead of timing out a few milliseconds before it.
  const deadline = Date.now() + 210_000;
  while (Date.now() < deadline) {
    const job = await apiFetch<SandboxJobResult>(`/jobs/${jobId}`);
    if (TERMINAL_JOB_STATUSES.has(job.status)) return job;
    await new Promise((resolve) => setTimeout(resolve, 750));
  }
  throw new Error('PRINT_STATUS_TIMEOUT');
}

type SandboxTemplateRef = Pick<Template, 'id' | 'paperProfileId'> & Partial<Pick<Template, 'engine'>>;

/**
 * Each paper profile has an HTML companion template generated by the API.
 * Resolving it here lets a paper-first sandbox workflow render without making
 * the operator select the same profile again through a template.
 */
export function getCompanionTemplateId(templates: SandboxTemplateRef[], paperProfileId: string): string {
  return templates.find(
    (template) => template.paperProfileId === paperProfileId && template.engine === 'HTML',
  )?.id ?? '';
}

/** A deliberately selected paper profile always wins over a template default. */
export function resolvePaperProfileId(currentPaperProfileId: string, template?: SandboxTemplateRef): string {
  return currentPaperProfileId || template?.paperProfileId || '';
}

const STATUS_DOT: Record<string, string> = {
  idle: 'var(--semantic-success)', online: 'var(--semantic-success)', busy: 'var(--semantic-progress)',
  offline: 'var(--semantic-error)', error: 'var(--semantic-error)', unknown: 'var(--semantic-neutral)',
};

const DEFAULT_PAYLOAD = '{"label":"Test Label","barcode":"ABC123","hn_masked":"HN***"}';

// ---- shared styles (consistent with PaperProfiles page) ----
const inputStyle: React.CSSProperties = {
  width: '100%', padding: 'var(--spacing-sm) 0.6rem', border: '1px solid var(--neutral-border-strong)',
  borderRadius: 'var(--rounded-md)', font: 'inherit', fontSize: 'var(--font-body-size)',
};
const labelStyle: React.CSSProperties = {
  display: 'block', marginBottom: '0.25rem', fontSize: 'var(--font-label-size)',
  fontWeight: 'var(--font-label-weight)', color: 'var(--neutral-text)',
};
const sectionStyle: React.CSSProperties = { borderBottom: '1px solid var(--neutral-border)', padding: '0.85rem 0' };
const sectionLastStyle: React.CSSProperties = { padding: '0.85rem 0' };
const sectionTitleStyle: React.CSSProperties = {
  fontSize: 'var(--font-mono-size)', fontWeight: 700, color: 'var(--neutral-deep)',
  textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: '0.6rem',
};
const primaryBtn: React.CSSProperties = {
  padding: '0.6rem 1.2rem', border: 0, borderRadius: 'var(--rounded-md)', background: 'var(--neutral-deep)',
  color: 'var(--neutral-surface)', cursor: 'pointer', fontWeight: 600, fontSize: 'var(--font-body-size)',
};
const secondaryBtn: React.CSSProperties = {
  padding: '0.6rem 1.2rem', border: '1px solid var(--neutral-border-strong)', borderRadius: 'var(--rounded-md)',
  background: 'var(--neutral-surface)', color: 'var(--neutral-text)', cursor: 'pointer', fontWeight: 600, fontSize: 'var(--font-body-size)',
};
const fieldBtn: React.CSSProperties = {
  padding: '0.45rem 0.6rem', border: '1px solid var(--neutral-border-strong)', borderRadius: 'var(--rounded-md)',
  background: 'var(--neutral-surface)', cursor: 'pointer', fontSize: 'var(--font-mono-size)', flex: 1,
  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.35rem',
};
const activeFieldBtn: React.CSSProperties = {
  background: 'var(--neutral-deep)', color: 'var(--neutral-surface)', borderColor: 'var(--neutral-deep)',
};
const cardStyle: React.CSSProperties = {
  background: 'var(--neutral-surface)', padding: '0 var(--spacing-xl)', borderRadius: 'var(--rounded-lg)', boxShadow: 'var(--shadow-subtle)',
};

export default function TemplateSandbox() {
  const { t } = useLocale();
  const [templates, setTemplates] = useState<Template[]>([]);
  const [papers, setPapers] = useState<Paper[]>([]);
  const [printers, setPrinters] = useState<Printer[]>([]);

  const [templateId, setTemplateId] = useState('');
  const [paperProfileId, setPaperProfileId] = useState('');
  const [printerId, setPrinterId] = useState('');
  const [payload, setPayload] = useState(DEFAULT_PAYLOAD);

  // Print options
  const [copies, setCopies] = useState(1);
  const [duplex, setDuplex] = useState(false);
  const [colorMode, setColorMode] = useState<'auto' | 'color' | 'monochrome'>('auto');
  const [priority, setPriority] = useState<'low' | 'normal' | 'high' | 'urgent'>('normal');

  const [preview, setPreview] = useState<Preview | null>(null);
  const [loading, setLoading] = useState({ init: true, render: false, print: false });
  const [error, setError] = useState('');
  const [toast, setToast] = useState<{ type: 'success' | 'error'; msg: string } | null>(null);
  const [confirmPrintOpen, setConfirmPrintOpen] = useState(false);
  const [printAcknowledged, setPrintAcknowledged] = useState(false);
  const [submittedJobId, setSubmittedJobId] = useState<string | null>(null);

  // ---- load reference data ----
  // Each list was `.catch(() => {})`: a failure left the three dropdowns empty
  // and the operator with no way to tell "nothing configured" from "the API is
  // down" — on the one page whose whole purpose is diagnosing print setup.
  const fetchReferenceData = useCallback(async () => {
    const [templates, papers, printers] = await Promise.all([
      apiFetch<Template[]>('/v1/sandbox/templates'),
      apiFetch<Paper[]>('/v1/paper-profiles'),
      apiFetch<Printer[]>('/printers'),
    ]);
    return { templates, papers, printers };
  }, []);

  const reference = useApiResource(fetchReferenceData);

  useEffect(() => {
    if (!reference.data) return;
    setTemplates(reference.data.templates);
    setPapers(reference.data.papers);
    setPrinters(reference.data.printers);
    setLoading((s) => ({ ...s, init: false }));
  }, [reference.data]);

  useEffect(() => {
    if (reference.error != null) setLoading((s) => ({ ...s, init: false }));
  }, [reference.error]);

  const selectedTemplate = useMemo(() => templates.find((t) => t.id === templateId), [templates, templateId]);
  const selectedPrinter = useMemo(() => printers.find((p) => p.id === printerId), [printers, printerId]);

  // ---- toast auto-dismiss ----
  useEffect(() => {
    if (!toast) return;
    const timer = setTimeout(() => setToast(null), 4000);
    return () => clearTimeout(timer);
  }, [toast]);

  // ---- JSON validation ----
  const payloadError = useMemo(() => {
    try { JSON.parse(payload); return ''; } catch { return t('page.sandbox.jsonError'); }
  }, [payload]);

  const printerMaxCopies = selectedPrinter?.maxCopiesPerJob ?? selectedPrinter?.capabilities?.maxCopies;
  const duplexAvailable = Boolean(selectedPrinter?.capabilities?.duplexSupported);
  const colorAvailable = Boolean(selectedPrinter?.capabilities?.colorSupported);
  const copiesExceeded = printerMaxCopies != null && copies > printerMaxCopies;
  const templateAllowed = !selectedPrinter?.allowedTemplates || selectedPrinter.allowedTemplates.length === 0 || !selectedTemplate || selectedPrinter.allowedTemplates.includes(selectedTemplate.templateCode);
  const printerReady = selectedPrinter?.status?.code === 'online' || selectedPrinter?.status?.code === 'idle';
  const canPrint = !!printerId && !!templateId && !payloadError && !copiesExceeded && templateAllowed && printerReady;
  const testPrintBlockedReason = !printerId
    ? t('page.sandbox.testPrintNeedsPrinter')
    : !templateId
      ? t('page.sandbox.testPrintNeedsTemplate')
      : payloadError
        ? t('page.sandbox.testPrintFixPayload')
        : copiesExceeded
          ? t('page.sandbox.testPrintReduceCopies')
          : !templateAllowed
            ? t('page.sandbox.testPrintChooseAllowedTemplate')
            : !printerReady
              ? 'The selected printer is not ready for physical output. Choose a printer reported as online or idle.'
            : '';

  useEffect(() => {
    if (!duplexAvailable && duplex) setDuplex(false);
    if (!colorAvailable && colorMode === 'color') setColorMode('auto');
  }, [colorAvailable, colorMode, duplex, duplexAvailable]);

  function handlePaperProfileChange(nextPaperProfileId: string) {
    setPaperProfileId(nextPaperProfileId);
    setPreview(null);
    setError('');

    const companionTemplateId = getCompanionTemplateId(templates, nextPaperProfileId);
    if (companionTemplateId) setTemplateId(companionTemplateId);
  }

  function handleTemplateChange(nextTemplateId: string) {
    const nextTemplate = templates.find((template) => template.id === nextTemplateId);
    setTemplateId(nextTemplateId);
    setPaperProfileId((currentPaperProfileId) => resolvePaperProfileId(currentPaperProfileId, nextTemplate));
    setPreview(null);
    setError('');
  }

  // ---- actions ----
  async function renderPreview() {
    setError('');
    if (!templateId) { setError(t('page.sandbox.selectTemplateFirst')); return; }
    if (payloadError) { setError(payloadError); return; }
    setLoading((s) => ({ ...s, render: true }));
    try {
      const res = await apiFetch<Preview>('/v1/sandbox/render-preview', {
        method: 'POST',
        body: JSON.stringify({
          templateId,
          paperProfileId: paperProfileId || undefined,
          samplePayload: JSON.parse(payload) as Record<string, unknown>,
        }),
      });
      setPreview(res);
    } catch (err: unknown) {
      // A template that fails to render says WHY (bad placeholder, missing
      // paper profile); the generic sentence hid every one of those reasons.
      setError(`${t('page.sandbox.renderFailed')} ${errorMessage(err)}`);
    } finally {
      setLoading((s) => ({ ...s, render: false }));
    }
  }

  async function testPrint() {
    setError('');
    if (!canPrint) { setError(t('page.sandbox.printIncomplete')); return; }
    setLoading((s) => ({ ...s, print: true }));
    try {
      const res = await apiFetch<{
        accepted: boolean;
        jobId: string;
        traceId: string;
        status: string;
        warnings: string[];
        errorCode?: string;
        errorMessage?: string;
      }>('/v1/sandbox/test-print', {
        method: 'POST',
        body: JSON.stringify({
          templateId,
          paperProfileId: paperProfileId || undefined,
          printerId,
          printerCode: selectedPrinter?.code,
          copies,
          duplex,
          colorMode,
          priority,
          samplePayload: JSON.parse(payload) as Record<string, unknown>,
        }),
      });
      setSubmittedJobId(res.jobId);
      const completed = await waitForSandboxJob(res.jobId);
      if (completed.status === 'SUCCESS') {
        setToast({ type: 'success', msg: t('page.sandbox.printSuccess').replace('{jobId}', res.jobId.slice(0, 8)).replace('{copies}', String(copies)).replace('{printer}', selectedPrinter?.name ?? '') });
      } else {
        const summary = t('page.sandbox.printFailed').replace('{status}', completed.status);
        setToast({ type: 'error', msg: completed.errorMessage ? `${summary}: ${completed.errorMessage}` : summary });
      }
    } catch (err) {
      setToast({
        type: 'error',
        msg: err instanceof Error && err.message === 'PRINT_STATUS_TIMEOUT'
          ? t('page.sandbox.printStatusTimeout')
          : `${t('page.sandbox.printError')} ${errorMessage(err)}`,
      });
    } finally {
      setLoading((s) => ({ ...s, print: false }));
    }
  }

  function requestTestPrint() {
    if (!canPrint) { setError(t('page.sandbox.printIncomplete')); return; }
    setPrintAcknowledged(false);
    setConfirmPrintOpen(true);
  }

  return (
    <div className="template-sandbox-page" style={{ position: 'relative' }}>
      <h1 style={{ marginBottom: '0.25rem' }}>{t('page.sandbox.title')}</h1>
      <p style={{ color: 'var(--neutral-text-muted)', marginBottom: 'var(--spacing-lg)', fontSize: '0.9rem' }}>
        {t('page.sandbox.description')}
      </p>

      {/* Reference data failed: the dropdowns below are empty because of this,
          not because nothing is configured. */}
      {reference.error != null && (
        <ErrorBanner
          error={reference.error}
          title={t('page.sandbox.referenceLoadFailed')}
          onRetry={reference.refresh}
        />
      )}

      {/* ===== Toast ===== */}
      {toast && (
        <div style={{
          position: 'fixed', top: 16, right: 16, zIndex: 2000,
          padding: '0.7rem var(--spacing-lg)', borderRadius: 'var(--rounded-lg)',
          background: toast.type === 'success' ? 'var(--state-success-surface)' : 'var(--state-danger-surface)',
          color: toast.type === 'success' ? 'var(--state-success-text)' : 'var(--state-danger-text)',
          fontWeight: 600, fontSize: 'var(--font-body-size)', boxShadow: 'var(--shadow-floating)',
        }}>
          {toast.msg}
        </div>
      )}
      <Dialog
        open={confirmPrintOpen}
        onClose={() => setConfirmPrintOpen(false)}
        title="Confirm physical test print"
        warning="This action will produce physical output. Generating a proof does not print."
        footer={<>
          <button type="button" style={secondaryBtn} onClick={() => setConfirmPrintOpen(false)}>Cancel</button>
          <button type="button" style={{ ...primaryBtn, ...(printAcknowledged && !loading.print ? {} : { opacity: 0.5, cursor: 'not-allowed' }) }} disabled={!printAcknowledged || loading.print} onClick={() => { setConfirmPrintOpen(false); void testPrint(); }}>
            {loading.print ? t('page.sandbox.sending') : 'Send physical test print'}
          </button>
        </>}
      >
        <dl className="sandbox-confirmation-summary">
          <dt>Printer</dt><dd>{selectedPrinter?.name ?? '—'}</dd>
          <dt>Template</dt><dd>{selectedTemplate?.templateCode ?? '—'}</dd>
          <dt>Copies</dt><dd>{copies}</dd>
        </dl>
        <label className="sandbox-confirmation-ack">
          <input type="checkbox" checked={printAcknowledged} onChange={(event) => setPrintAcknowledged(event.target.checked)} />
          I understand this will produce physical output.
        </label>
      </Dialog>

      {loading.init ? (
        <p className="loading-text">{t('page.sandbox.loading')}</p>
      ) : (
        <div className="template-sandbox-layout">
          {/* ===================== Config Panel ===================== */}
          <section style={cardStyle}>
            {/* --- Printer --- */}
            <div style={{ ...sectionStyle, paddingTop: '1.1rem' }}>
              <div style={sectionTitleStyle}>{t('page.sandbox.printer')}</div>
              <label style={labelStyle}>{t('page.sandbox.selectPrinter')}</label>
              <select aria-label={t('page.sandbox.selectPrinter')} style={inputStyle} value={printerId} onChange={(e) => setPrinterId(e.target.value)}>
                <option value="">{t('page.sandbox.selectPrinterPlaceholder')}</option>
                {printers.filter((p) => p.isActive).map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.name} ({p.code}){p.location ? ` · ${p.location}` : ''}
                    {p.status ? ` · ${p.status.code}` : ''}
                  </option>
                ))}
              </select>
              <p id="sandbox-capability-status" role="status" aria-live="polite" style={{ margin: 'var(--spacing-xs) 0 0', color: 'var(--neutral-text-muted)', fontSize: 'var(--font-label-size)' }}>
                {!selectedPrinter
                  ? t('page.sandbox.selectPrinterForOptions')
                  : [!duplexAvailable && t('page.sandbox.duplexUnavailable'), !colorAvailable && t('page.sandbox.colorUnavailable')].filter(Boolean).join(' ')}
              </p>
              {selectedPrinter && (
                <div style={{ marginTop: '0.5rem', display: 'flex', flexWrap: 'wrap', gap: '0.35rem' }}>
                  {selectedPrinter.status && (
                    <span style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 'var(--font-label-size)', padding: '0.15rem var(--spacing-sm)', background: 'var(--neutral-subtle)', borderRadius: 'var(--rounded-sm)' }}>
                      <span style={{ width: 8, height: 8, borderRadius: '50%', background: STATUS_DOT[selectedPrinter.status.code] ?? 'var(--semantic-neutral)', display: 'inline-block' }} />
                      {selectedPrinter.status.code}
                    </span>
                  )}
                  <span style={{ fontSize: 'var(--font-label-size)', padding: '0.15rem var(--spacing-sm)', background: 'var(--neutral-subtle)', borderRadius: 'var(--rounded-sm)' }}>{selectedPrinter.protocol}</span>
                  {selectedPrinter.capabilities?.duplexSupported && <span style={{ fontSize: 'var(--font-label-size)', padding: '0.15rem var(--spacing-sm)', background: 'var(--neutral-subtle)', borderRadius: 'var(--rounded-sm)' }}>{t('page.sandbox.duplexLabel')}</span>}
                  {selectedPrinter.capabilities?.colorSupported && <span style={{ fontSize: 'var(--font-label-size)', padding: '0.15rem var(--spacing-sm)', background: 'var(--neutral-subtle)', borderRadius: 'var(--rounded-sm)' }}>{t('page.sandbox.colorLabel')}</span>}
                  {printerMaxCopies != null && <span style={{ fontSize: 'var(--font-label-size)', padding: '0.15rem var(--spacing-sm)', background: 'var(--neutral-subtle)', borderRadius: 'var(--rounded-sm)' }}>{t('page.sandbox.maxCopiesLabel').replace('{n}', String(printerMaxCopies))}</span>}
                </div>
              )}
              {!templateAllowed && (
                <div style={{ marginTop: '0.4rem', padding: '0.4rem 0.55rem', background: 'var(--state-warning-surface)', color: 'var(--state-warning-text)', borderRadius: 'var(--rounded-sm)', fontSize: 'var(--font-label-size)' }}>
                  ⚠️ {t('page.sandbox.templateNotAllowed').replace('{code}', selectedTemplate?.templateCode ?? '')}
                </div>
              )}
            </div>

            {/* --- Paper & Template --- */}
            <div style={sectionStyle}>
              <div style={sectionTitleStyle}>{t('page.sandbox.templatePaper')}</div>
              <div style={{ marginBottom: '0.5rem' }}>
                <label style={labelStyle}>{t('page.sandbox.paperProfile')}</label>
                <select aria-label={t('page.sandbox.paperProfile')} style={inputStyle} value={paperProfileId} onChange={(e) => handlePaperProfileChange(e.target.value)}>
                  <option value="">{t('page.sandbox.paperProfileDefault')}</option>
                  {papers.map((p) => (
                    <option key={p.id} value={p.id}>{p.code} ({p.widthMm}×{p.heightMm}mm, {p.dpi}dpi)</option>
                  ))}
                </select>
                {paperProfileId && (
                  <p style={{ margin: '0.3rem 0 0', color: 'var(--neutral-text-muted)', fontSize: 'var(--font-label-size)' }}>
                    {t('page.sandbox.paperProfilePriorityHint')}
                  </p>
                )}
              </div>
              <div>
                <label style={labelStyle}>{t('page.sandbox.template')}</label>
                <select aria-label={t('page.sandbox.template')} style={inputStyle} value={templateId} onChange={(e) => handleTemplateChange(e.target.value)}>
                  <option value="">{t('page.sandbox.selectTemplatePlaceholder')}</option>
                  {templates.map((t) => (
                    <option key={t.id} value={t.id}>{t.templateCode} — {t.name}</option>
                  ))}
                </select>
                {selectedTemplate && (
                  <div style={{ marginTop: '0.3rem', display: 'flex', gap: '0.35rem', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: 'var(--font-label-size)', padding: '0.15rem var(--spacing-sm)', background: 'var(--neutral-subtle)', borderRadius: 'var(--rounded-sm)' }}>{selectedTemplate.engine}</span>
                    <span style={{ fontSize: 'var(--font-label-size)', padding: '0.15rem var(--spacing-sm)', background: 'var(--neutral-subtle)', borderRadius: 'var(--rounded-sm)' }}>{selectedTemplate.status}</span>
                  </div>
                )}
              </div>
            </div>

            {/* --- Print Options --- */}
            <div style={sectionStyle}>
              <div style={sectionTitleStyle}>{t('page.sandbox.printOptions')}</div>
              <div style={{ marginBottom: '0.6rem' }}>
                <label style={labelStyle}>{t('page.sandbox.copies')}</label>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                  <button
                    type="button"
                    style={{ ...secondaryBtn, padding: '0.35rem 0.7rem', fontSize: '0.9rem' }}
                    onClick={() => setCopies(Math.max(1, copies - 1))}
                  >
                    −
                  </button>
                  <input
                    aria-label={t('page.sandbox.copies')}
                    type="number"
                    min={1}
                    style={{ ...inputStyle, width: 64, textAlign: 'center' }}
                    value={copies}
                    onChange={(e) => setCopies(Math.max(1, Number(e.target.value) || 1))}
                  />
                  <button
                    type="button"
                    style={{ ...secondaryBtn, padding: '0.35rem 0.7rem', fontSize: '0.9rem' }}
                    onClick={() => setCopies(copies + 1)}
                  >
                    +
                  </button>
                </div>
                {copiesExceeded && (
                  <div style={{ marginTop: '0.3rem', padding: 'var(--spacing-xs) var(--spacing-sm)', background: 'var(--state-danger-surface)', color: 'var(--state-danger-text)', borderRadius: 'var(--rounded-sm)', fontSize: 'var(--font-label-size)' }}>
                    {t('page.sandbox.copiesExceeded').replace('{max}', String(printerMaxCopies))}
                  </div>
                )}
              </div>

              {/* Duplex */}
              <div style={{ marginBottom: '0.6rem' }}>
                <label style={labelStyle}>{t('page.sandbox.duplex')}</label>
                <div style={{ display: 'flex', gap: '0.4rem' }}>
                  <button type="button" style={{ ...fieldBtn, ...(!duplex ? activeFieldBtn : {}) }} onClick={() => setDuplex(false)}>
                    {t('page.sandbox.singleSided')}
                  </button>
                  <button
                    type="button"
                    style={{ ...fieldBtn, ...(duplex ? activeFieldBtn : {}), ...(!duplexAvailable ? { opacity: 0.5, cursor: 'not-allowed' } : {}) }}
                    onClick={() => setDuplex(true)}
                    disabled={!duplexAvailable}
                    aria-describedby={!duplexAvailable ? 'sandbox-capability-status' : undefined}
                  >
                    ⇄ {t('page.sandbox.doubleSidedShort')}
                  </button>
                </div>
              </div>

              {/* Color Mode */}
              <div style={{ marginBottom: '0.6rem' }}>
                <label style={labelStyle}>{t('page.sandbox.colorMode')}</label>
                <div style={{ display: 'flex', gap: '0.4rem' }}>
                  {(['auto', 'color', 'monochrome'] as const).map((m) => (
                    <button
                      key={m}
                      type="button"
                      style={{ ...fieldBtn, ...(colorMode === m ? activeFieldBtn : {}), ...(m === 'color' && !colorAvailable ? { opacity: 0.5, cursor: 'not-allowed' } : {}) }}
                      onClick={() => setColorMode(m)}
                      disabled={m === 'color' && !colorAvailable}
                      aria-describedby={m === 'color' && !colorAvailable ? 'sandbox-capability-status' : undefined}
                    >
                      {m === 'auto' ? t('page.sandbox.auto') : m === 'color' ? t('page.sandbox.color') : t('page.sandbox.monochrome')}
                    </button>
                  ))}
                </div>
              </div>

              {/* Priority */}
              <div>
                <label style={labelStyle}>{t('page.sandbox.priority')}</label>
                <div style={{ display: 'flex', gap: '0.4rem' }}>
                  {(['low', 'normal', 'high', 'urgent'] as const).map((p) => (
                    <button
                      key={p}
                      type="button"
                      style={{ ...fieldBtn, ...(priority === p ? activeFieldBtn : {}) }}
                      onClick={() => setPriority(p)}
                    >
                      {p === 'urgent' ? '🔴' : p === 'high' ? '🟠' : p === 'normal' ? '🟢' : '⚪'} {p.charAt(0).toUpperCase() + p.slice(1)}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* --- Payload --- */}
            <details style={sectionLastStyle}>
              <summary style={{ ...sectionTitleStyle, cursor: 'pointer' }}>Expert payload</summary>
              <p style={{ margin: '0 0 var(--spacing-sm)', color: 'var(--neutral-text-muted)', fontSize: 'var(--font-label-size)' }}>Edit JSON only when troubleshooting a template proof.</p>
              <textarea
                aria-label={t('page.sandbox.samplePayload')}
                value={payload}
                onChange={(e) => setPayload(e.target.value)}
                rows={6}
                style={{
                  ...inputStyle, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                  fontSize: '0.78rem', resize: 'vertical',
                  ...(payloadError ? { borderColor: 'var(--semantic-error)', background: 'var(--state-danger-surface)' } : {}),
                }}
              />
              {payloadError && (
                <div style={{ marginTop: '0.3rem', color: 'var(--semantic-error)', fontSize: 'var(--font-label-size)' }}>{payloadError}</div>
              )}
            </details>

            {/* --- Actions --- */}
            {error && (
              <div style={{ padding: '0.55rem 0.7rem', background: 'var(--state-danger-surface)', color: 'var(--state-danger-text)', borderRadius: 'var(--rounded-md)', fontSize: 'var(--font-mono-size)', marginBottom: '0.6rem' }}>
                {error}
              </div>
            )}
            <div style={{ display: 'flex', gap: '0.5rem', paddingBottom: '1.1rem' }}>
              <button type="button" style={primaryBtn} onClick={() => void renderPreview()} disabled={loading.render}>
                {loading.render ? t('page.sandbox.rendering') : t('page.sandbox.renderPreview')}
              </button>
              <button
                type="button"
                style={{ ...primaryBtn, ...(canPrint && !loading.print ? {} : { opacity: 0.5, cursor: 'not-allowed' }) }}
                onClick={requestTestPrint}
                disabled={!canPrint || loading.print}
                aria-describedby={!canPrint ? 'sandbox-test-print-status' : undefined}
              >
                {loading.print ? t('page.sandbox.sending') : t('page.sandbox.testPrint')}
              </button>
            </div>
            {submittedJobId && (
              <p role="status" aria-live="polite" style={{ margin: '0 0 1.1rem', color: 'var(--neutral-text-muted)', fontSize: 'var(--font-label-size)' }}>
                Physical test print submitted. <a href={`/jobs/${submittedJobId}`}>Open job {submittedJobId.slice(0, 8)}</a> to check its latest status.
              </p>
            )}
            {!canPrint && (
              <p id="sandbox-test-print-status" role="status" aria-live="polite" style={{ margin: '0 0 1.1rem', color: 'var(--neutral-text-muted)', fontSize: 'var(--font-label-size)' }}>
                {t('page.sandbox.testPrintBlocked').replace('{reason}', testPrintBlockedReason)}
              </p>
            )}
          </section>

          {/* ===================== Preview Panel ===================== */}
          <section style={{ ...cardStyle, padding: '1.25rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
              <h2 style={{ fontSize: 'var(--font-subheading-size)', margin: 0, color: 'var(--neutral-deep)' }}>{t('page.sandbox.preview')}</h2>
              {preview && (
                <span style={{ fontSize: 'var(--font-label-size)', color: 'var(--neutral-text-muted)' }}>render {preview.renderTimeMs}ms</span>
              )}
            </div>

            {!preview ? (
              <div style={{
                minHeight: 320, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                background: 'var(--neutral-page)', borderRadius: 'var(--rounded-lg)', color: 'var(--neutral-text-muted)', textAlign: 'center', padding: 'var(--spacing-3xl)',
              }}>
                <span style={{ fontSize: 'calc(var(--font-stat-size) + var(--spacing-sm))', marginBottom: 'var(--spacing-sm)' }}>🖨️</span>
                <p style={{ fontSize: '0.85rem' }}>{t('page.sandbox.previewEmpty')}</p>
              </div>
            ) : (
              <>
                {/* Preview canvas (Variant 1: Print Proof Workbench) */}
                <div className="sandbox-proof-workbench">
                  <div className="sandbox-proof-toolbar">
                    <span className="sandbox-proof-dim">
                      📐 {papers.find((p) => p.id === paperProfileId)?.code ?? 'Print Canvas'} ({papers.find((p) => p.id === paperProfileId) ? `${papers.find((p) => p.id === paperProfileId)!.widthMm}×${papers.find((p) => p.id === paperProfileId)!.heightMm}mm, ${papers.find((p) => p.id === paperProfileId)!.dpi} DPI` : 'Standard Proof'})
                    </span>
                    <span className="sandbox-proof-latency">⚡ {preview.renderTimeMs}ms</span>
                  </div>
                  <div className="sandbox-paper-sheet">
                    <div dangerouslySetInnerHTML={{ __html: sanitizePreviewHtml(preview.renderedPreview) }} />
                  </div>
                </div>

                {/* Warnings */}
                {preview.warnings.length > 0 && (
                  <div style={{ marginTop: '0.6rem', padding: '0.55rem 0.7rem', background: 'var(--state-warning-surface)', color: 'var(--state-warning-text)', borderRadius: 'var(--rounded-md)', fontSize: 'var(--font-label-size)' }}>
                    <strong>{t('page.sandbox.warnings')}:</strong>
                    <ul style={{ margin: '0.3rem 0 0 1rem', padding: 0 }}>
                      {preview.warnings.map((w, i) => <li key={i}>{w}</li>)}
                    </ul>
                  </div>
                )}

                {/* Generated payload */}
                <div style={{ marginTop: '0.8rem' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.3rem' }}>
                    <h3 style={{ fontSize: 'var(--font-mono-size)', fontWeight: 700, color: 'var(--neutral-deep)', textTransform: 'uppercase', letterSpacing: '0.04em', margin: 0 }}>
                      {t('page.sandbox.generatedPayload')}
                    </h3>
                    <button
                      type="button"
                      style={{ ...secondaryBtn, padding: '0.25rem 0.55rem', fontSize: '0.72rem' }}
                      onClick={() => navigator.clipboard.writeText(preview.renderedPrintPayload)}
                    >
                      {t('common.copy')}
                    </button>
                  </div>
                  <pre style={{
                    whiteSpace: 'pre-wrap', wordBreak: 'break-all', maxHeight: 240, overflow: 'auto',
                    margin: 0, padding: '0.7rem', background: 'var(--neutral-deep)', color: 'var(--nav-text)', borderRadius: 'var(--rounded-md)',
                    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace', fontSize: '0.75rem',
                  }}>
                    {preview.renderedPrintPayload}
                  </pre>
                </div>
              </>
            )}

            {/* Print summary */}
            {(selectedPrinter || selectedTemplate) && (
              <div style={{ marginTop: '0.8rem', padding: '0.6rem var(--spacing-md)', background: 'var(--state-info-surface)', border: '1px solid var(--semantic-info)', borderRadius: 'var(--rounded-md)', fontSize: 'var(--font-label-size)', color: 'var(--state-info-text)' }}>
                <strong>{t('page.sandbox.printSummary')}:</strong>{' '}
                {selectedPrinter?.name ?? t('page.sandbox.summaryNoPrinter')}
                {' · '}
                {t('page.sandbox.copiesUnit').replace('{n}', String(copies))}
                {' · '}
                {duplex ? t('page.sandbox.doubleSidedShort') : t('page.sandbox.singleSidedShort')}
                {' · '}
                {colorMode === 'color' ? t('page.sandbox.colorShort') : colorMode === 'monochrome' ? t('page.sandbox.monochromeShort') : t('page.sandbox.auto')}
                {' · '}
                {priority}
                {selectedTemplate && ` · ${selectedTemplate.templateCode}`}
              </div>
            )}
          </section>
        </div>
      )}
    </div>
  );
}
